const styleHeaderRoad = {
  Header: {
    position: 'absolute',
    top: 0,
    width: '100%',
    height: '120px',
    backgroundColor: 'white',
    zIndex: 100,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  HeaderIn: {
    display: 'flex',
    justifyContent: 'center',
  },
  address: {
    top: '10px',
    position: 'absolute',
    zIndex: 90,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    transform: 'translateX(0)',
    transition: 'all 0.4s ease-in-out;',
  },
  inputRoad: {
    margin: '5px',
    padding: 0,
    height: '20px',
  },
  adresseValidation: {
    top: '10px',
    position: 'absolute',
    zIndex: 110,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    transform: 'translateX(-9999px)',
    transition: 'all 0.4s ease-in-out;',
  },
  validatorOut: {
    top: '10px',
    position: 'absolute',
    zIndex: 115,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    transform: 'translateX(-9999px)',
    transition: 'all 0.4s ease-in-out;',
  },
  Validator: {
    top: '10px',
    position: 'absolute',
    zIndex: 90,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    transform: 'translateX(0)',
    transition: 'all 0.4s ease-in-out;',
  },
  input: {
    margin: '1px',
  },
  textfield: {
    borderRadius: '10px',
    border: 'none',
    backgroundColor: '#F1F1F1',
    margin: '0.2em',
    padding: '0.4em',
  },
};

export default styleHeaderRoad;
